
spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_ENDPOINT}/${SPRING_DATASOURCE_NAME}?sslmode=verify-full&currentSchema=authapi
    continue-on-error: true
    hikari:
      pool-name: AuthorizationServer-CP
      connectionTimeout: 1000
      validationTimeout: 500

  flyway:
    default-schema: authapi
