ALTER TABLE OAUTH2_REGISTERED_CLIENT ADD JWT_FIELDS varchar(1000) DEFAULT NULL;
ALTER TABLE OAUTH2_REGISTERED_CLIENT ADD MFA varchar(10) DEFAULT NULL;
ALTER TABLE OAUTH2_REGISTERED_CLIENT ADD MFA_REMEMBER_ME boolean DEFAULT false;
