ALTER TABLE OAUTH2_USER_AUTHORIZATION_CODE
DROP CONSTRAINT IF EXISTS OAUTH2_USER_AUTHORIZATION_CODE_ID_FKEY;

ALTER TABLE OAUTH2_USER_AUTHORIZATION_CODE
    ADD CONSTRAINT OAUTH2_USER_AUTHORIZATION_CODE_ID_FKEY
        FOREIGN KEY (ID)
            REFERENCES OAUTH2_AUTHORIZATION(ID)
            ON DELETE CASCADE;
