ALTER TABLE OAUTH2_REGISTERED_CLIENT DROP COLUMN JIRA;
ALTER TABLE OAUTH2_REGISTERED_CLIENT DROP COLUMN DATABASE_USERNAME;
ALTER TABLE OAUTH2_REGISTERED_CLIENT RENAME COLUMN SKIP_TO_AZURE_FIELD to SKIP_TO_AZURE;
