ALTER TABLE OAUTH2_AUTHORIZATION
    DROP oidc_id_token_value,
    DROP oidc_id_token_issued_at,
    DROP oidc_id_token_expires_at,
    DROP oidc_id_token_metadata,
    DROP refresh_token_value,
    DROP refresh_token_issued_at,
    DROP refresh_token_expires_at,
    DROP refresh_token_metadata,
    DROP user_code_value,
    DROP user_code_issued_at,
    DROP user_code_expires_at,
    DROP user_code_metadata,
    DROP device_code_value,
    DROP device_code_issued_at,
    DROP device_code_expires_at,
    DROP device_code_metadata;