---
generic-service:
  nameOverride: hmpps-authorization-server

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-authorization-server
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-authorization-server-cert
    contextColour: green

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-authorization-server:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      JWT_KEYSTORE_PASSWORD: "JWT_KEYSTORE_PASSWORD"
      JWT_SIGNING_KEY_PAIR: "JWT_SIGNING_KEY_PAIR"

    dps-rds-instance-output:
      SPRING_DATASOURCE_NAME: "database_name"
      SPRING_DATASOURCE_ENDPOINT: "rds_instance_endpoint"
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-authorization-server
