---
# Per environment values which override defaults in hmpps-authorization-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: authorization-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    BASE_URL: https://authorization-api-dev.hmpps.service.justice.gov.uk
    HMPPS_AUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
